### ISSUE TITLE
ROS release of any_node

### ISSUE THREAD

**Issue by mikekaram** [ANYbotics/any_node#1]
Hello,

we want to release a ROS package which depends on `any_node`. I created a [repo](https://github.com/mikekaram/any_node-release) to release `any_node` into ROS. However, I really think that this repo belongs under the Anybotics roof. If there is an issue with this move, please let me know.

Cheers,
Mike

**Comment by remod** [comment]
Closing for the same reason as in https://github.com/ANYbotics/message_logger/issues/1
